services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    command: nodemon npm start
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    volumes:
      - ./src:/app/src
